### ISSUE TITLE
tester leaks

### ISSUE THREAD

**Issue by murmurlab** [murmurlab/projects#4]
my main output:

https://github.com/murmurlab/ecole42kocaeli/blob/main/42cursus/get_next_line/main.c

ahbasara@k2m17s07 get_next_line % cc -Wall -Wextra -Werror get_next_line.c get_next_line_utils.c main.c
ahbasara@k2m17s07 get_next_line % ./a.out
fd: 3

Process:         a.out [4308]
Path:            /Volumes/VOLUME/*/a.out
Load Address:    0x10126d000
Identifier:      a.out
Version:         ???
Code Type:       X86-64
Parent Process:  zsh [1803]

Date/Time:       2023-01-22 13:19:05.586 +0300
Launch Time:     2023-01-22 13:19:05.130 +0300
OS Version:      Mac OS X 10.15.7 (19H15)
Report Version:  7
Analysis Tool:   /Applications/Xcode.app/Contents/Developer/usr/bin/leaks
Analysis Tool Version:  Xcode 12.3 (12C33)

Physical footprint:         328K
Physical footprint (peak):  328K

leaks Report Version: 4.0
Process 4308: 157 nodes malloced for 12 KB
Process 4308: 0 leaks for 0 total leaked bytes.

so no leaks
---

Trpolliue tester

git clone https://github.com/xicodomingues/gnlTester to https://github.com/murmurlab/ecole42kocaeli/blob/main/42cursus/get_next_line/

ahbasara@k2m17s07 gnlTester % make m     
Already up to date.
[Mandatory]
[BUFFER_SIZE = 1]: 
Invalid fd: 1.OK 2.OK 3.OK 
files/empty: 1.OK 2.OK 
files/nl: 1.OK 2.KO LEAKS.KO [0x7fd1a1c05980 : 1]  ------------------THIS IS LEAK
files/41_no_nl: 1.KO 2.KO LEAKS.KO [0x7fd1a1d04240 : 1] 
files/41_with_nl: 1.OK 2.OK 3.KO LEAKS.KO [0x7fd1a1c05800 : 1]

**Comment by hu8813** [comment]
merhaba Ahmet, valgrind adli programlar test ettim. normalde linux icin ama mac de de docker araciligiyla yükleyebilirsin.
cok fazla memory hatasi ve 1 tane leak var. muhtemelen okudugun dosyanin sonuna gelince free yapmayi unuttun static variable i. ayrica substr funksiyonunu bi kontrol et, genelde o hataya neden oluyor, len - start dan fazla kesmemesi lazim substr sanirim

programin dosya bittikten sonra okunacak birsey kalmayinca (null) yazmasi gerekirken rastgele memoryden characterleri yaziyor

**Comment by murmurlab** [comment]
> merhaba Ahmet, valgrind adli programlar test ettim. normalde linux icin ama mac de de docker araciligiyla yükleyebilirsin. cok fazla memory hatasi ve 1 tane leak var. muhtemelen okudugun dosyanin sonuna gelince free yapmayi unuttun static variable i. ayrica substr funksiyonunu bi kontrol et, genelde o hataya neden oluyor, len - start dan fazla kesmemesi lazim substr sanirim
> 
> programin dosya bittikten sonra okunacak birsey kalmayinca (null) yazmasi gerekirken rastgele memoryden characterleri yaziyor

projede 1 tane static var kullanabiliyormusuz bu yuzden ve buffer arrayini surekli BUFFER_SIZE kadar tutmaya calistigimdan (gerek yok boyle birseye zaten line BUFFER_SIZE dan buyuk olabilir) bastan yapiyorum
